USE[OB]
/*********************************************************
--  程式名稱：電銷每月分派名單產生
--  功能說明：依照名單設定撈取案件，計算更新各名單數量
--  撰寫人員：
--  開發日期：
--  修改日期：

-- 
-- 檢查:
SELECT LIST_NO,LIST_NM,TOTAL_AMOUNT,CARD_TYPE 
FROM OBMLISTDF WITH(NOLOCK) 
WHERE PROJECT_WORKYM='202312'
*********************************************************/
	DECLARE @MSG NVARCHAR(MAX)='',
			@WORKDT VARCHAR(10)='20260401' -- 下月一號日期 yyyyMM01


	IF (DATEPART(D,GETDATE())<'21' AND NOT GETDATE() BETWEEN '20240101' AND '20240110') OR  @WORKDT < convert(varchar(10),GETDATE(),112)	 --正式用21
	--IF DATEPART(D,GETDATE())<'01' OR  @WORKDT < convert(varchar(10),GETDATE(),112)	--測試用01
	BEGIN
		RETURN    -- 執行時間日期<21號 、 @WORKDT<現在時間 => 不給執行，因為已派案
	END 
	ELSE BEGIN
		BEGIN TRAN 
		BEGIN TRY

			DECLARE @BREAK VARCHAR(200)=''
			DECLARE @LIST_NO VARCHAR(15)=''
			DECLARE @LIST_NM VARCHAR(50)=''
			DECLARE @CASENUMBER VARCHAR(50)=''
			DECLARE @CARD_TYPE VARCHAR(5)=''	--客戶分級卡 ADD BY JOAN 20191127
			--DECLARE @TIER_LEVEL VARCHAR(5)=''	--20210120 MinYann 依據TIER分配給部門和人員
			--DECLARE @MSG VARCHAR(200)
			--SELECT LIST_NO,LIST_NM,CASENUMBER,CARD_TYPE FROM OBMLISTDF WHERE PROJECT_WORKYM='202305'

			DECLARE cur_list CURSOR FOR -- SEC
			SELECT LIST_NO, LIST_NM, CASENUMBER, CARD_TYPE  FROM OBMLISTDF WITH (NOLOCK)
			WHERE PROJECT_WORKYM = LEFT(@WORKDT,6) -- 取下月的名單

			OPEN cur_list
				FETCH NEXT FROM cur_list INTO @LIST_NO, @LIST_NM, @CASENUMBER, @CARD_TYPE
					WHILE(@@FETCH_STATUS = 0)
					BEGIN

						SET @BREAK='@LIST_NO='+@LIST_NO+', @LIST_NM='+@LIST_NM
						PRINT @BREAK

						DECLARE @IS_ASSIGNED VARCHAR(1)

						SELECT TOP 1 @IS_ASSIGNED=IS_ASSIGNED
						  FROM OBMLISTDF
						 WHERE LIST_NO=@LIST_NO

						--ADD BY JOAN 20191224 加客戶分級卡(CARD_TYPE)，取自名單名稱後三碼
						UPDATE OBMLISTDF 
						SET CARD_TYPE =RIGHT(LIST_NM,3-CHARINDEX('-',RIGHT(LIST_NM,3)) )
						WHERE LIST_NO=@LIST_NO

						--SELECT @CARD_TYPE=CARD_TYPE FROM OBMLISTDF WHERE LIST_NO=@LIST_NO

						-- 依照名單設定分案
						IF ISNULL( @IS_ASSIGNED,'N')<>'Y' 
						BEGIN 
							PRINT  'SP_INFOT_ASSIGNEXPORTNAMELIST_st1_list'
							PRINT GETDATE()
							EXEC [dbo].[SP_INFOT_ASSIGNEXPORTNAMELIST_st1_list] @MSG OUTPUT, @LIST_NO
							IF ISNULL(@MSG,'')<>''
							BEGIN 
								--RETURN
								RAISERROR (15600,-1,-1, @MSG);  
							END

							-- 更新數量
							UPDATE OBMLISTDF
							SET ASSIGNED_DATE=GETDATE(),
								TOTAL_AMOUNT =(SELECT COUNT(1) FROM OBPOOLDATA_LIST  WHERE LIST_NO=@LIST_NO),
								RESERVED_AMOUNT=(SELECT COUNT(1) FROM OBPOOLDATA_LIST  WHERE LIST_NO=@LIST_NO AND ISNULL(OB_DEPT,'') =''),
								U_SYSDT=GETDATE(),
								U_USERID='SYSTEM',
								U_PRGID ='EST'
							WHERE LIST_NO=@LIST_NO
						END

						FETCH NEXT FROM cur_list INTO @LIST_NO,@LIST_NM,@CASENUMBER,@CARD_TYPE

					END --WHILE

			CLOSE cur_list
			DEALLOCATE cur_list


		END TRY
		BEGIN CATCH
			CLOSE cur_list
			DEALLOCATE cur_list
			ROLLBACK

			SET @MSG= @BREAK + ', ERROR:' + ISNULL(ERROR_MESSAGE(),'') 
			PRINT  @MSG

		END CATCH
	END

	COMMIT