USE[OB]


/*
在名單類型已經有設定完成時再執行


參數可都留空白，遇到工作日特別少時，可透過改變發放日起訖調配數量
SELECT MAX(CASEDT) 已派案日 FROM OBASSIGNSET WITH(NOLOCK)
WHERE WORKDT<=FORMAT(GETDATE(),'yyyyMM01')




*/



/*估算每日分派案件數量*/
IF DATEPART(DD,GETDATE())>='21' OR GETDATE() BETWEEN '20240101' AND '20240110'	--正式用21
	--IF DATEPART(DD,GETDATE())>='01'	--測試用01
	BEGIN 
        DECLARE @WORKDT VARCHAR(10);			-- 下個月年月
		DECLARE @WORKDT_MONTH VARCHAR(10);		-- 下個月1號
		DECLARE @OVERRIDE_DATE_FIRST VARCHAR(10)='';    -- 發放日起，留空為不修改
		DECLARE @OVERRIDE_DATE_LAST VARCHAR(10)='';     --發放日訖，留空不修改

		DECLARE   @WORKDAYS INT=0 -- 工作天數
				, @RATIO_DAY INT=0 -- 工作天分配比例
				, @DATE_FIRST DATE -- 當月第一個工作天日期
				, @DATE_LAST DATE --當月最後一個工作天日期

		DECLARE @MSG VARCHAR(300);

		SET @WORKDT_MONTH = LEFT(CONVERT(VARCHAR(10), DATEADD(MONTH,1,GETDATE()), 112),6);	-- 下個月年月 [yyyyMM]
        SET @WORKDT = @WORKDT_MONTH +'01';													-- 下個月1號 [yyyyMM01]	

		SET @DATE_FIRST = IIF(ISNULL(@OVERRIDE_DATE_FIRST,'')<>'' AND ISDATE(@OVERRIDE_DATE_FIRST)=1,@OVERRIDE_DATE_FIRST,@WORKDT)
		SET @DATE_LAST = IIF(ISNULL(@OVERRIDE_DATE_LAST,'')<>'' AND ISDATE(@OVERRIDE_DATE_LAST)=1,@OVERRIDE_DATE_LAST,EOMONTH(@WORKDT,0))
		--SELECT @WORKDT AS [@WORKDT], @WORKDT_MONTH AS [@WORKDT_MONTH]
		

		IF (SELECT COUNT(1) FROM [dbo].[OBASSIGNSET] WHERE WORKDT=@WORKDT) = 0 
		BEGIN 
			DELETE FROM [dbo].[OBASSIGNSET] WHERE WORKDT=@WORKDT

			IF OBJECT_ID('tempdb..#MONTH') IS NOT NULL DROP TABLE #MONTH
			SELECT  CONVERT(VARCHAR(10), CALENDAR_DATE,112) AS CASEDT -- 工作天日期
					, CAST(0 AS INT) AS RATION	-- 工作天比例
					, ROW_NUMBER() OVER(ORDER BY CALENDAR_DATE DESC) AS SEQ -- 排序(分配剩餘比例用，日期比較晚的先被分)
			INTO #MONTH
			FROM OBCALENDAR
			WHERE REST_FLG=0 
			--AND LEFT(CONVERT(VARCHAR, CALENDAR_DATE, 112),6) = @WORKDT_MONTH
			AND CALENDAR_DATE BETWEEN @DATE_FIRST AND @DATE_LAST

			--計算每日的分配比率
			--以1000除以工作天數，再把餘數平分至每一天
			SELECT @WORKDAYS = COUNT(1) FROM #MONTH -- 取工作天數

			UPDATE A
			SET A.RATION = FLOOR(1000/@WORKDAYS) -- 每日平分比例（無條件捨去）
			FROM #MONTH A

			UPDATE A
			SET A.RATION = A.RATION + 1
			FROM #MONTH A
			WHERE A.SEQ <= (1000 % @WORKDAYS) -- 依序補回剩餘比例

			--3.寫入分配檔
			INSERT INTO OBASSIGNSET(LIST_NO, WORKDT, CASEDT, RATIO_RATE)
			SELECT A.LIST_NO, @WORKDT, B.CASEDT, B.RATION
			  FROM OBMLISTDF A
			  JOIN #MONTH B ON 1=1
			 WHERE PROJECT_WORKYM = @WORKDT_MONTH

			 ----大概看一下結果
			 --select * from OBASSIGNSET with(nolock)
			 --where WORKDT like '202604%'

			 --select LIST_NO, LIST_NM, CASENUMBER, CARD_TYPE,* 
			 --from OBMLISTDF with(nolock)
			 --where PROJECT_WORKYM like '202604%'
			 
		END
		END