USE [OB]
GO

/****** Object:  StoredProcedure [dbo].[USP_OBZ020_XML]    Script Date: 2026/5/28 上午 11:30:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/**********************************************************************************
 * 系統名稱：OB
 * 程式名稱：[USP_OBZ020_XML] 
 * 功能說明： - XML處理
 * 撰寫日期：2022/09/14
 * 撰寫人員：Rumin
 * 維護日期：
 * 維護人員：

BEGIN TRANSACTION
 EXEC USP_OBZ020_XML '<ROOT><E1><LIST_NM>202210測測測測</LIST_NM><PROD_KIND>01</PROD_KIND><LIST_PERIOD_START>4</LIST_PERIOD_START><LIST_PERIOD_END>60</LIST_PERIOD_END><LIST_INTERVAL>4</LIST_INTERVAL><SETTLE_SRC>Y$$N</SETTLE_SRC><ACTIONCD>I</ACTIONCD><GRIDID>20220920164111</GRIDID><MTDT /><LIST_TYPE>01$$03</LIST_TYPE><CASEYEAR>0$$2</CASEYEAR><SPEC_TP>01$$02$$03$$99</SPEC_TP></E1><M1 /></ROOT>' 
 ,'SAVE','02','','','',0,''
ROLLBACK TRANSACTION 

BEGIN TRANSACTION
 EXEC USP_OBZ020_XML '<ROOT><L1><ROW><ROWNO>1</ROWNO><LIST_NO>OB209908001</LIST_NO><LIST_NM>209907期中客戶名單_他新中古-H</LIST_NM><TOTAL_AMOUNT>3,214</TOTAL_AMOUNT><DEPT_RATE /><FNC_01>OB209908001</FNC_01><FNC_02>OB209908001</FNC_02><FNC_03>OB209908001</FNC_03><ACTIONCD /><GRIDSTATUS /><GRIDID>637989420687207878</GRIDID><SELECT>Y</SELECT></ROW><ROW><ROWNO>2</ROWNO><LIST_NO>OB202209013</LIST_NO><LIST_NM>202209期中商品-HC</LIST_NM><TOTAL_AMOUNT>179</TOTAL_AMOUNT><DEPT_RATE /><FNC_01>OB202209013</FNC_01><FNC_02>OB202209013</FNC_02><FNC_03>OB202209013</FNC_03><ACTIONCD /><GRIDSTATUS /><GRIDID>637989420687207879</GRIDID><SELECT>Y</SELECT></ROW></L1></ROOT>'
 ,'COPY','02','','','',0,''
ROLLBACK TRANSACTION 

BEGIN TRANSACTION
EXEC USP_OBZ020_XML '<ROOT><E1><LIST_NO>OB202210022</LIST_NO><LIST_NM>202210TTTTEST</LIST_NM><PROD_KIND>03</PROD_KIND><SPEC_TP>01$$02</SPEC_TP><LIST_TYPE>01</LIST_TYPE><LIST_PERIOD_START>7</LIST_PERIOD_START><LIST_PERIOD_END>120</LIST_PERIOD_END><LIST_INTERVAL>4</LIST_INTERVAL><CASEYEAR>0$$1$$2</CASEYEAR><SETTLE_SRC>Y$$N</SETTLE_SRC><ACTIONCD>U</ACTIONCD><GRIDID>20220922092107</GRIDID></E1><M1><ROW><LIST_NO>OB202210022</LIST_NO><OBDEPTID>XVE1</OBDEPTID><OBDEPTNM>北區電銷1</OBDEPTNM><RATION>50.1</RATION><ACTIONCD>U</ACTIONCD><GRIDID>637994352675608728</GRIDID></ROW><ROW><LIST_NO>OB202210022</LIST_NO><OBDEPTID>XVE2</OBDEPTID><OBDEPTNM>南區電銷</OBDEPTNM><RATION>49.9</RATION><ACTIONCD>U</ACTIONCD><GRIDID>637994352675608729</GRIDID></ROW></M1></ROOT>'
,'SAVE','02','','','',0,''
ROLLBACK TRANSACTION 
**********************************************************************************/
ALTER PROCEDURE [dbo].[USP_OBZ020_XML]
	-- Add the parameters for the stored procedure here
	@I_XML_DATA         XML,
	@I_CHR_FLAG         VARCHAR(20),			--儲存SAVE, 複製COPY, 計算案件數COUNT, 刪除部門比例DELETE_RATE
	@I_CHR_COMPID		VARCHAR(10),			--公司代碼
	
	@I_CHR_MTUSERID		VARCHAR(20),			--資料維護者
	@I_CHR_MTPGMID		VARCHAR(20),			--資料維護程式代碼
	@O_CHR_MSGTYPE		CHAR(2)			OUTPUT,	--訊息類別
	@O_INT_MSGLEVEL		INT				OUTPUT,	--訊息LEVEL
	@O_CHR_MESSAGE		NVARCHAR(100)	OUTPUT	--訊息
AS

--放要複製或計算的名單(L1)
CREATE TABLE #TEMP_L1
	(	GRIDID				VARCHAR(20),		--GRID ID
		ACTIONCD		    VARCHAR(1),         --I/U/D
		ROWNO				INT,				--前端畫面序號
		LIST_NO				VARCHAR(11),		--名單代號
		LIST_NM				NVARCHAR(45),		--名單名字
	)
--放E1資料
CREATE TABLE #TEMP_E1
	(	GRIDID				VARCHAR(20),		--GRID ID
		ACTIONCD		    VARCHAR(1),         --I/U/D
		LIST_NO				VARCHAR(11),		--名單代號(不可修改)
		LIST_NM				NVARCHAR(45),		--名單名字
		PROD_KIND			VARCHAR(255),		--商品類型(汽車/機車/商品)
		SPEC_TP				VARCHAR(255),		--專案類別
		LIST_TYPE			VARCHAR(255),		--名單類型(期中/滿期/中結)
		LIST_PERIOD_START	VARCHAR(3),			--開始撈取期數
		LIST_PERIOD_END		VARCHAR(3),			--結束撈取期數
		LIST_INTERVAL		VARCHAR(3),			--間隔期數
		CASEYEAR			VARCHAR(255),		--進件/滿期/中結年數
		SETTLE_SRC			VARCHAR(6),			--被他行代償案件
	)

CREATE TABLE #TEMP_RE1
	(	GRIDID               VARCHAR(20),       --GRID ID
		ACTIONCD             VARCHAR(1),        --I/U/D 
		LIST_NO	 			 VARCHAR(11),		--名單代號
		PROD_KIND			 VARCHAR(255),		--商品類型(汽車/機車/商品)
		IS_SET_DEPT_RATE	 NVARCHAR(50),		--是否設定部門比例
		MTDT                 DATETIME			--維護日期
    )

--放M1資料
CREATE TABLE #TEMP_M1 
	(
		GRIDID				VARCHAR(20),		--GRID ID
        ACTIONCD			VARCHAR(1),			--I/U/D	
		LIST_NO				VARCHAR(11),		--名單代號
		OBDEPTID			VARCHAR(4),			--部門代號
		OBDEPTNM			NVARCHAR(10),		--部門名稱
		RATION				VARCHAR(4)			--部門比例
	)

--放更新後要回傳到M1的資料
CREATE TABLE #TEMP_RM1 
	(
		GRIDID				VARCHAR(20),		--GRID ID
		ACTIONCD			VARCHAR(1),			--I/U/D 
		MTDT				DATETIME			--維護日期
	)

BEGIN
	DECLARE @CHR_USPNAME		VARCHAR(30),
			@INT_ERR_NUM		INT,
			@INT_ROW_NUM		INT,
			@CHR_ERR_MSG		NVARCHAR(300),
			@INT_ROWCOUNT		INT,
			@CHR_ERMSG_PAR		NVARCHAR(100),
			@CHR_MESSAGE		NVARCHAR(500),

			@ERR_PROC			VARCHAR(30),
			@ERR_NUM			INT,
			@ERR_MSG			NVARCHAR(500),
			@ERR_SEVERITY		INT,
			@ERR_STATE			INT,
			@ERR_LINE			INT

	DECLARE @INT_IDOC			INT

	--FOR 回傳畫面欄位
	DECLARE	@DTE_MTDT_O			DATETIME,
			@CHR_LIST_NO_O		VARCHAR(11) --名單代號

	--FOR CURSOR欄位
	DECLARE	@CHR_GRIDID				VARCHAR(20),		--GRID ID
			@CHR_ACTIONCD			VARCHAR(1),			--I/U/D			 
			@CHR_ROWNO				INT,				--前端畫面序號
			@CHR_LIST_NO			VARCHAR(11),		--名單代號
			@CHR_LIST_NM			NVARCHAR(45),		--名單名字
			@CHR_PROD_KIND			VARCHAR(255),		--商品類型(汽車/機車/商品)
			@CHR_SPEC_TP			VARCHAR(255),		--專案類別
			@CHR_LIST_TYPE			VARCHAR(255),		--名單類型(期中/滿期/中結)
			@CHR_LIST_PERIOD_START	VARCHAR(3),			--開始撈取期數
			@CHR_LIST_PERIOD_END	VARCHAR(3),			--結束撈取期數
			@CHR_LIST_INTERVAL		VARCHAR(3),			--間隔期數
			@CHR_CASEYEAR			VARCHAR(255),		--進件/滿期/中結年數
			@CHR_SETTLE_SRC			VARCHAR(6),			--被他行代償案件
			@CHR_OBDEPTID			VARCHAR(4),			--部門代號
			@CHR_OBDEPTNM			NVARCHAR(10),		--部門名稱
			@NUM_RATION				NUMERIC(4,1)		--部門比例
	   

	SET NOCOUNT ON;
	SET @CHR_USPNAME  = 'USP_OBZ020_XML'
	SET @O_CHR_MSGTYPE = ''
	SET @O_CHR_MESSAGE = ''
	SET @DTE_MTDT_O = GETDATE()
	SET @CHR_LIST_NO_O = ''

	--測試用
	--select @I_XML_DATA XML
	--INTO ##TMP_TEST

	--測試用
	--INSERT INTO [dbo].[TestTable]([DT])
	--VALUES(@I_XML_DATA)
	--select * from  TestTable

	BEGIN TRAN
		
		EXEC sp_xml_preparedocument @INT_IDOC OUTPUT, @I_XML_DATA

		INSERT INTO #TEMP_L1 
				(	GRIDID, ACTIONCD, ROWNO, LIST_NO, LIST_NM	)
		SELECT	GRIDID, ACTIONCD, ROWNO, LIST_NO, LIST_NM               
		FROM OPENXML(@INT_IDOC, '/ROOT/L1/ROW', 2) WITH #TEMP_L1
		
		INSERT INTO #TEMP_E1 
				(	GRIDID, ACTIONCD, LIST_NO, LIST_NM, PROD_KIND, 
				SPEC_TP,LIST_TYPE, LIST_PERIOD_START, LIST_PERIOD_END, LIST_INTERVAL, CASEYEAR,SETTLE_SRC	)
		SELECT	GRIDID, ACTIONCD, LIST_NO, LIST_NM, PROD_KIND, 
				SPEC_TP, LIST_TYPE, LIST_PERIOD_START, LIST_PERIOD_END, LIST_INTERVAL, CASEYEAR, SETTLE_SRC              
		FROM OPENXML(@INT_IDOC, '/ROOT/E1', 2) WITH #TEMP_E1
		
		INSERT INTO #TEMP_M1 
				(	GRIDID, ACTIONCD, LIST_NO, OBDEPTID, OBDEPTNM, RATION	)						   		
		SELECT	GRIDID, ACTIONCD, LIST_NO, OBDEPTID, OBDEPTNM, RATION
				--MVALUE = CONVERT(decimal(8,2),CASE WHEN ISNULL(MVALUE,'')='' THEN 0 ELSE MVALUE END), 
				--MVALUE = CAST(CASE WHEN ISNULL(MVALUE,'')='' THEN 0 ELSE MVALUE END AS DECIMAL(8,2)), 
		FROM OPENXML(@INT_IDOC, '/ROOT/M1/ROW', 2) WITH #TEMP_M1

		EXEC sp_xml_removedocument @INT_IDOC

		--select * from  #TEMP_M1
		--select * from  #TEMP_E1	
		--select * from  #TEMP_L1

	/* 處理COPY 名單複製 */
	IF @I_CHR_FLAG = 'COPY'
	BEGIN
		DECLARE GET_L1 CURSOR LOCAL FOR
		SELECT	GRIDID, ACTIONCD, ROWNO, LIST_NO, LIST_NM    
		FROM	#TEMP_L1
		ORDER BY ROWNO DESC  --D/I/U

		OPEN GET_L1
		FETCH GET_L1 INTO @CHR_GRIDID, @CHR_ACTIONCD, @CHR_ROWNO, @CHR_LIST_NO, @CHR_LIST_NM
		
		WHILE (@@FETCH_STATUS = 0)
			BEGIN	
			BEGIN TRY            
				EXEC USP_OBZ020_COPY 
				 @CHR_LIST_NO 				
				,@I_CHR_MTUSERID					--資料維護者 
				,@I_CHR_MTPGMID						--資料維護程式代碼
				,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
				,@O_INT_MSGLEVEL		OUTPUT		--訊息LEVEL 
				,@O_CHR_MESSAGE			OUTPUT		--訊息			

				IF @O_INT_MSGLEVEL <> 0
					BEGIN
						RAISERROR(N'',16,1)
					END
			END TRY
			BEGIN CATCH
				IF ERROR_NUMBER() <> 0
					BEGIN
						IF @@TRANCOUNT > 0
							ROLLBACK TRAN

						CLOSE GET_L1
						DEALLOCATE GET_L1
						SELECT	@ERR_PROC = ERROR_PROCEDURE(), 
								@ERR_NUM = ERROR_NUMBER(), 
								@ERR_MSG = @O_CHR_MESSAGE + dbo.USF_ERROR_MESSAGE(ERROR_MESSAGE()), @ERR_SEVERITY = ERROR_SEVERITY(), @ERR_STATE = ERROR_STATE(), @ERR_LINE = ERROR_LINE()
						SELECT 'EE' AS TYPE, @CHR_GRIDID AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
						RAISERROR (N'%s,%d,%s,%d,%d,%d,%s',16,1, @ERR_PROC, @ERR_NUM, @ERR_MSG, @ERR_SEVERITY, @ERR_STATE, @ERR_LINE, @O_CHR_MESSAGE)
						RETURN
				   END
			END CATCH
					
			FETCH GET_L1 INTO @CHR_GRIDID, @CHR_ACTIONCD, @CHR_ROWNO, @CHR_LIST_NO, @CHR_LIST_NM

		END --WHILE
		CLOSE GET_L1
		DEALLOCATE GET_L1
		--select * from OBMLISTDF order by LIST_NO desc
	END

	/* 處理COUNT 計算名單 */
	IF @I_CHR_FLAG = 'COUNT'
	BEGIN
		DECLARE GET_L1 CURSOR LOCAL FOR
		SELECT	GRIDID, ACTIONCD, ROWNO, LIST_NO    
		FROM	#TEMP_L1
		ORDER BY ROWNO DESC  --D/I/U

		OPEN GET_L1
		FETCH GET_L1 INTO @CHR_GRIDID, @CHR_ACTIONCD, @CHR_ROWNO, @CHR_LIST_NO
		
		WHILE (@@FETCH_STATUS = 0)
			BEGIN	
			BEGIN TRY            
				EXEC USP_OBZ020_COUNT 
				 @CHR_LIST_NO 				
				,@I_CHR_MTUSERID					--資料維護者 
				,@I_CHR_MTPGMID						--資料維護程式代碼
				,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
				,@O_INT_MSGLEVEL		OUTPUT		--訊息LEVEL 
				,@O_CHR_MESSAGE			OUTPUT		--訊息

				IF @O_INT_MSGLEVEL <> 0
					BEGIN
						RAISERROR(N'',16,1)
					END
			END TRY
			BEGIN CATCH
				IF ERROR_NUMBER() <> 0
					BEGIN
						IF @@TRANCOUNT > 0
							ROLLBACK TRAN

						CLOSE GET_L1
						DEALLOCATE GET_L1
						SELECT	@ERR_PROC = ERROR_PROCEDURE(), 
								@ERR_NUM = ERROR_NUMBER(), 
								@ERR_MSG = @O_CHR_MESSAGE + dbo.USF_ERROR_MESSAGE(ERROR_MESSAGE()), @ERR_SEVERITY = ERROR_SEVERITY(), @ERR_STATE = ERROR_STATE(), @ERR_LINE = ERROR_LINE()
						SELECT 'EE' AS TYPE, @CHR_GRIDID AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
						RAISERROR (N'%s,%d,%s,%d,%d,%d,%s',16,1, @ERR_PROC, @ERR_NUM, @ERR_MSG, @ERR_SEVERITY, @ERR_STATE, @ERR_LINE, @O_CHR_MESSAGE)
						RETURN
				   END
			END CATCH
					
			FETCH GET_L1 INTO @CHR_GRIDID, @CHR_ACTIONCD, @CHR_ROWNO, @CHR_LIST_NO

		END --WHILE
		CLOSE GET_L1
		DEALLOCATE GET_L1
	END

	/* 處理DELETE_RATE 刪除部門比例 */
	IF @I_CHR_FLAG = 'DELETE_RATE'
	BEGIN

		SELECT	@CHR_GRIDID=GRIDID, @CHR_ACTIONCD=ACTIONCD, @CHR_LIST_NO=LIST_NO
		FROM	#TEMP_E1
		BEGIN TRY            
			EXEC USP_OBZ020_DEL_DEPT_RATE 
			 @CHR_LIST_NO 				
			,@I_CHR_MTUSERID					--資料維護者 
			,@I_CHR_MTPGMID						--資料維護程式代碼
			,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
			,@O_INT_MSGLEVEL		OUTPUT		--訊息LEVEL 
			,@O_CHR_MESSAGE			OUTPUT		--訊息

			IF @O_INT_MSGLEVEL <> 0
				BEGIN
					RAISERROR(N'',16,1)
				END

			-- 重新select結果更新回前端畫面
			EXEC USP_OBZ020_S10 
			 @CHR_LIST_NO 				
			,@I_CHR_MTUSERID					--資料維護者 
			,@I_CHR_MTPGMID						--資料維護程式代碼
			,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
			,@O_INT_MSGLEVEL		OUTPUT		--訊息LEVEL 
			,@O_CHR_MESSAGE			OUTPUT		--訊息

		END TRY
		BEGIN CATCH
			IF ERROR_NUMBER() <> 0
				BEGIN
					IF @@TRANCOUNT > 0
						ROLLBACK TRAN

					CLOSE GET_L1
					DEALLOCATE GET_L1
					SELECT	@ERR_PROC = ERROR_PROCEDURE(), 
							@ERR_NUM = ERROR_NUMBER(), 
							@ERR_MSG = @O_CHR_MESSAGE + dbo.USF_ERROR_MESSAGE(ERROR_MESSAGE()), @ERR_SEVERITY = ERROR_SEVERITY(), @ERR_STATE = ERROR_STATE(), @ERR_LINE = ERROR_LINE()
					SELECT 'EE' AS TYPE, @CHR_GRIDID AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
					RAISERROR (N'%s,%d,%s,%d,%d,%d,%s',16,1, @ERR_PROC, @ERR_NUM, @ERR_MSG, @ERR_SEVERITY, @ERR_STATE, @ERR_LINE, @O_CHR_MESSAGE)
					RETURN
			   END
		END CATCH					
	END

	/* 處理儲存 */
	IF @I_CHR_FLAG = 'SAVE'
	BEGIN
		--E1處理
		DECLARE GET_E1 CURSOR LOCAL FOR
		SELECT	GRIDID, ACTIONCD, LIST_NO, LIST_NM, PROD_KIND, SPEC_TP, LIST_TYPE, 
				LIST_PERIOD_START, LIST_PERIOD_END, LIST_INTERVAL, CASEYEAR, SETTLE_SRC
		FROM	#TEMP_E1
		ORDER BY ACTIONCD  --D/I/U

		OPEN GET_E1
		FETCH GET_E1 INTO @CHR_GRIDID, @CHR_ACTIONCD, @CHR_LIST_NO, @CHR_LIST_NM, @CHR_PROD_KIND, @CHR_SPEC_TP, @CHR_LIST_TYPE, 
						  @CHR_LIST_PERIOD_START, @CHR_LIST_PERIOD_END, @CHR_LIST_INTERVAL, @CHR_CASEYEAR, @CHR_SETTLE_SRC
		
		WHILE (@@FETCH_STATUS = 0)
			BEGIN	
				IF @CHR_ACTIONCD = 'I'		--E1新增
					BEGIN
						BEGIN TRY            
							EXEC USP_OBZ020_I00	  @CHR_LIST_NM			
												 ,@CHR_PROD_KIND			
												 ,@CHR_SPEC_TP			
												 ,@CHR_LIST_TYPE			
												 ,@CHR_LIST_PERIOD_START	
												 ,@CHR_LIST_PERIOD_END	
												 ,@CHR_LIST_INTERVAL		
												 ,@CHR_CASEYEAR			
												 ,@CHR_SETTLE_SRC			

												 ,@I_CHR_MTUSERID						--資料維護者 
												 ,@I_CHR_MTPGMID						--資料維護程式代碼
												 ,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
												 ,@O_INT_MSGLEVEL			OUTPUT		--訊息LEVEL 
												 ,@O_CHR_MESSAGE			OUTPUT		--訊息
												 ,@CHR_LIST_NO_O			OUTPUT		--因新增而產生的名單ID
							
							IF @O_INT_MSGLEVEL <> 0
								BEGIN
									RAISERROR(N'',16,1)
								END
							INSERT INTO #TEMP_RE1 VALUES(@CHR_GRIDID, @CHR_ACTIONCD, @CHR_LIST_NO_O, @CHR_PROD_KIND, '',@DTE_MTDT_O)
						END TRY
						BEGIN CATCH						
						ROLLBACK TRAN

						CLOSE GET_E1
						DEALLOCATE GET_E1
						SELECT	@ERR_PROC = ERROR_PROCEDURE(), 
								@ERR_NUM = ERROR_NUMBER(), 
								@ERR_MSG = @O_CHR_MESSAGE + dbo.USF_ERROR_MESSAGE(ERROR_MESSAGE()), @ERR_SEVERITY = ERROR_SEVERITY(), @ERR_STATE = ERROR_STATE(), @ERR_LINE = ERROR_LINE()
						SELECT 'EE' AS TYPE, @CHR_GRIDID AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
						RAISERROR (N'%s,%d,%s,%d,%d,%d,%s',16,1, @ERR_PROC, @ERR_NUM, @ERR_MSG, @ERR_SEVERITY, @ERR_STATE, @ERR_LINE, @O_CHR_MESSAGE)
						RETURN
							 
						END CATCH
					END	--E1新增

				
				IF @CHR_ACTIONCD = 'U' --E1修改    

					BEGIN
						BEGIN TRY
							EXEC USP_OBZ020_U00	  @CHR_LIST_NO	
												 ,@CHR_LIST_NM			
												 ,@CHR_PROD_KIND			
												 ,@CHR_SPEC_TP			
												 ,@CHR_LIST_TYPE			
												 ,@CHR_LIST_PERIOD_START	
												 ,@CHR_LIST_PERIOD_END	
												 ,@CHR_LIST_INTERVAL		
												 ,@CHR_CASEYEAR			
												 ,@CHR_SETTLE_SRC			

												 ,@I_CHR_MTUSERID						--資料維護者 
												 ,@I_CHR_MTPGMID						--資料維護程式代碼
												 ,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
												 ,@O_INT_MSGLEVEL			OUTPUT		--訊息LEVEL 
												 ,@O_CHR_MESSAGE			OUTPUT		--訊息
							
							IF @O_INT_MSGLEVEL <> 0
								BEGIN
									RAISERROR(N'',16,1)
								END

							INSERT INTO #TEMP_RE1 VALUES(@CHR_GRIDID, @CHR_ACTIONCD, @CHR_LIST_NO, @CHR_PROD_KIND, '',@DTE_MTDT_O)
						END TRY
						BEGIN CATCH	
							IF ERROR_NUMBER() <> 0
								BEGIN
									IF @@TRANCOUNT > 0
										ROLLBACK TRAN

									CLOSE GET_E1
									DEALLOCATE GET_E1
									SELECT	@ERR_PROC = ERROR_PROCEDURE(), 
											@ERR_NUM = ERROR_NUMBER(), 
											@ERR_MSG = @O_CHR_MESSAGE + dbo.USF_ERROR_MESSAGE(ERROR_MESSAGE()), @ERR_SEVERITY = ERROR_SEVERITY(), @ERR_STATE = ERROR_STATE(), @ERR_LINE = ERROR_LINE()
									SELECT 'EE' AS TYPE, @CHR_GRIDID AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
									RAISERROR (N'%s,%d,%s,%d,%d,%d,%s',16,1, @ERR_PROC, @ERR_NUM, @ERR_MSG, @ERR_SEVERITY, @ERR_STATE, @ERR_LINE, @O_CHR_MESSAGE)
									RETURN
							   END
						END CATCH
					END	--E1修改  		   
				

				IF @CHR_ACTIONCD = 'D'  --E1刪除
					BEGIN
						BEGIN TRY
							EXEC USP_OBZ020_D00	  @CHR_LIST_NO
												 ,@I_CHR_MTUSERID						--資料維護者 
												 ,@I_CHR_MTPGMID						--資料維護程式代碼
												 ,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
												 ,@O_INT_MSGLEVEL			OUTPUT		--訊息LEVEL 
												 ,@O_CHR_MESSAGE			OUTPUT		--訊息

							IF @O_INT_MSGLEVEL <> 0
								BEGIN
									RAISERROR(N'',16,1)
								END
														
							INSERT INTO #TEMP_RE1 VALUES(@CHR_GRIDID, @CHR_ACTIONCD, @CHR_LIST_NO, @CHR_PROD_KIND, '',@DTE_MTDT_O)
						END TRY
						BEGIN CATCH
							IF ERROR_NUMBER() <> 0
								BEGIN
									IF @@TRANCOUNT > 0
										ROLLBACK TRAN

									CLOSE GET_E1
									DEALLOCATE GET_E1
									SELECT	@ERR_PROC = ERROR_PROCEDURE(), 
											@ERR_NUM = ERROR_NUMBER(), 
											@ERR_MSG = @O_CHR_MESSAGE + dbo.USF_ERROR_MESSAGE(ERROR_MESSAGE()), @ERR_SEVERITY = ERROR_SEVERITY(), @ERR_STATE = ERROR_STATE(), @ERR_LINE = ERROR_LINE()
									SELECT 'EE' AS TYPE, @CHR_GRIDID AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
									RAISERROR (N'%s,%d,%s,%d,%d,%d,%s',16,1, @ERR_PROC, @ERR_NUM, @ERR_MSG, @ERR_SEVERITY, @ERR_STATE, @ERR_LINE, @O_CHR_MESSAGE)
									RETURN
							   END
						END CATCH
					END	--E1刪除

		FETCH GET_E1 INTO @CHR_GRIDID, @CHR_ACTIONCD, @CHR_LIST_NO, @CHR_LIST_NM, @CHR_PROD_KIND, @CHR_SPEC_TP, @CHR_LIST_TYPE, 
						  @CHR_LIST_PERIOD_START, @CHR_LIST_PERIOD_END, @CHR_LIST_INTERVAL, @CHR_CASEYEAR, @CHR_SETTLE_SRC

		END --WHILE
		CLOSE GET_E1
		DEALLOCATE GET_E1
			

--		--M1 處理 
		DECLARE GET_M1 CURSOR LOCAL FOR
			SELECT	GRIDID, ACTIONCD, 
					LIST_NO, OBDEPTID, OBDEPTNM, 
					RATION=CONVERT(NUMERIC(4,1),CASE WHEN ISNULL(RATION,'')='' THEN '0' ELSE RATION END)
			FROM	#TEMP_M1
			ORDER BY	ACTIONCD  --D/I/U

		OPEN GET_M1
		FETCH GET_M1 INTO	@CHR_GRIDID, @CHR_ACTIONCD, 
							@CHR_LIST_NO, @CHR_OBDEPTID, @CHR_OBDEPTNM,
							@NUM_RATION

		WHILE (@@FETCH_STATUS = 0)
			BEGIN			

				IF @CHR_ACTIONCD = 'U'     --M區修改
				
					BEGIN
						BEGIN TRY
							EXEC USP_OBZ020_U10  @CHR_LIST_NO	
												,@CHR_OBDEPTID	
												,@NUM_RATION	
												
												,@I_CHR_MTUSERID					--資料維護者 
												,@I_CHR_MTPGMID						--資料維護程式代碼
												,@O_CHR_MSGTYPE			OUTPUT		--訊息類別
												,@O_INT_MSGLEVEL		OUTPUT		--訊息LEVEL 
												,@O_CHR_MESSAGE			OUTPUT		--訊息

							IF(@O_INT_MSGLEVEL > 0) BEGIN
								SET @O_CHR_MESSAGE = @O_CHR_MESSAGE
								RAISERROR('%s', 16, 1, @O_CHR_MESSAGE)
								END

							INSERT INTO #TEMP_RM1 VALUES(@CHR_GRIDID, @CHR_ACTIONCD,@DTE_MTDT_O)
							
							UPDATE #TEMP_RE1 SET IS_SET_DEPT_RATE='已設定'

						END TRY
						BEGIN CATCH
							IF ERROR_NUMBER() <> 0
								BEGIN
									 IF @@TRANCOUNT > 0
										ROLLBACK TRAN
									 CLOSE GET_M1
									 DEALLOCATE GET_M1
									 SELECT @ERR_PROC = ERROR_PROCEDURE(), 
											@ERR_NUM = ERROR_NUMBER(), 
											@ERR_MSG = @O_CHR_MESSAGE + dbo.USF_ERROR_MESSAGE(ERROR_MESSAGE()), @ERR_SEVERITY = ERROR_SEVERITY(), @ERR_STATE = ERROR_STATE(), @ERR_LINE = ERROR_LINE()
									 SELECT 'EE' AS TYPE, @CHR_GRIDID AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
									 RAISERROR (N'%s,%d,%s,%d,%d,%d,%s',16,1, @ERR_PROC, @ERR_NUM, @ERR_MSG, @ERR_SEVERITY, @ERR_STATE, @ERR_LINE, @O_CHR_MESSAGE)
									 RETURN
								END
						END CATCH
					END--M區修改

		FETCH GET_M1 INTO	@CHR_GRIDID, @CHR_ACTIONCD, 
							@CHR_LIST_NO, @CHR_OBDEPTID, @CHR_OBDEPTNM, @NUM_RATION

		END--WHILE
		CLOSE GET_M1
		DEALLOCATE GET_M1

	END
		
	DROP TABLE #TEMP_E1
	DROP TABLE #TEMP_M1

	SELECT 'E1' AS TYPE, GRIDID, ACTIONCD, LIST_NO, PROD_KIND, IS_SET_DEPT_RATE, MTDT
	FROM #TEMP_RE1

	SELECT 'M1' AS TYPE, GRIDID, ACTIONCD, MTDT
	FROM #TEMP_RM1	
	
	--FOR MESSAGE
	SELECT 'SS' AS TYPE, '' AS GRIDID, @O_CHR_MSGTYPE AS MSGTYPE, @O_INT_MSGLEVEL AS MSGLEVEL, @O_CHR_MESSAGE AS MESSAGE
	
	DROP TABLE #TEMP_RE1
	DROP TABLE #TEMP_RM1


--	ROLLBACK TRAN
	COMMIT TRAN

	SET NOCOUNT OFF
END
RETURN
GO


