USE [OB]
GO
/****** Object:  StoredProcedure [dbo].[USP_OBZ020_I00]    Script Date: 2026/5/28 上午 11:33:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/**********************************************************************************
 * 系統名稱：OB
 * 程式名稱：[USP_OBZ020_I00] 
 * 功能說明：OBZ020 電銷名單部門比例維護[新增]
 * 撰寫日期：2022/09/20
 * 撰寫人員：Rumin
 * 維護紀錄：
BEGIN TRAN
EXEC USP_OBZ020_I00 'OB202106003'
,'','','' ,0,''
ROLLBACK TRAN
**********************************************************************************/

ALTER PROCEDURE [dbo].[USP_OBZ020_I00]
(
	  @I_CHR_LIST_NM			NVARCHAR(45)		--名單名字
	 ,@I_CHR_PROD_KIND			VARCHAR(255)		--商品類型(汽車/機車/商品)
	 ,@I_CHR_SPEC_TP			VARCHAR(255)		--專案類別
	 ,@I_CHR_LIST_TYPE			VARCHAR(255)		--名單類型(期中/滿期/中結)
	 ,@I_CHR_LIST_PERIOD_START	VARCHAR(3)			--開始撈取期數
	 ,@I_CHR_LIST_PERIOD_END	VARCHAR(3)			--結束撈取期數
	 ,@I_CHR_LIST_INTERVAL		VARCHAR(3)			--間隔期數
	 ,@I_CHR_CASEYEAR			VARCHAR(255)		--進件/滿期/中結年數
	 ,@I_CHR_SETTLE_SRC			VARCHAR(6)			--被他行代償案件

	 ,@I_CHR_MTUSERID			NVARCHAR(14)			-- 資料維護者
	 ,@I_CHR_MTPGMID			NVARCHAR(20)			-- 資料維護程式代碼
	 ,@O_CHR_MSGTYPE			CHAR(2)			OUTPUT	-- 訊息類別
	 ,@O_INT_MSGLEVEL			INT				OUTPUT	-- 訊息LEVEL
	 ,@O_CHR_MESSAGE			NVARCHAR(200)	OUTPUT	-- 訊息
	 ,@O_CHR_LIST_NO			VARCHAR(11)		OUTPUT	-- 因新增而產生的名單ID
)
AS
BEGIN
	-- 輸入檢核 START
	IF(ISNULL(@I_CHR_LIST_NM,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'名單名字不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_PROD_KIND,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'商品類型不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_SPEC_TP,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'專案類別不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_LIST_TYPE,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'名單類型不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_LIST_PERIOD_START,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'開始撈取期數不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_LIST_PERIOD_END,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'結束撈取期數不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_LIST_INTERVAL,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'間隔期數不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_CASEYEAR,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'進件/滿期/中結年數不得為空！'
		RETURN    
	END 
	ELSE IF(ISNULL(@I_CHR_SETTLE_SRC,'')='')
	BEGIN
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'被他行代償案件不得為空！'
		RETURN    
	END 
	-- 輸入檢核 END


	DECLARE  @YM_NEW VARCHAR(10)=''
			,@NOW DATETIME=GETDATE()
	DECLARE  @LIST_NO_NEW VARCHAR(15)=''
			,@MAXNUM VARCHAR(10)
	SELECT	 @YM_NEW = LEFT(CONVERT(VARCHAR, DATEADD(MONTH, 1, @NOW), 112),6)		--現在時間的年月再加一個月，再轉格式YYYYMM

	-- 產生新的LISTNO
	IF NOT EXISTS (SELECT 1 FROM OBMLISTDF WHERE LIST_NO LIKE '%'+@YM_NEW+'%')
	BEGIN
		SET @LIST_NO_NEW='OB'+@YM_NEW+'001'	
	END
	ELSE
	BEGIN
		--找目前最大的號碼+1做為新的LISTNO號碼
		SET @MAXNUM=(SELECT MAX(CAST(RIGHT(LIST_NO,9)AS INT))+1 FROM OBMLISTDF WHERE LIST_NO LIKE '%'+@YM_NEW+'%')
		SET @LIST_NO_NEW='OB'+CAST(@MAXNUM AS VARCHAR)	
	END



	BEGIN TRY
		INSERT INTO OBMLISTDF
		([A_PRGID], [A_USERID], [A_SYSDT], [U_PRGID], [U_USERID], [U_SYSDT], 
		 [LIST_NO], [LIST_NM],
		 [PROD_KIND], [PROD_BEST], [SPEC_TP], [LIST_TYPE], [LIST_PERIOD_START], [LIST_PERIOD_END], [LIST_INTERVAL], [PROJECT_WORKYM], 
		[CASEYEAR], [SETTLE_SRC])
		SELECT 
		@I_CHR_MTPGMID, @I_CHR_MTUSERID, @NOW, @I_CHR_MTPGMID, @I_CHR_MTUSERID, @NOW, 
		@LIST_NO_NEW, @I_CHR_LIST_NM,
		@I_CHR_PROD_KIND, 'Y', @I_CHR_SPEC_TP, @I_CHR_LIST_TYPE, @I_CHR_LIST_PERIOD_START, @I_CHR_LIST_PERIOD_END, @I_CHR_LIST_INTERVAL, @YM_NEW, 
		@I_CHR_CASEYEAR, @I_CHR_SETTLE_SRC

		SET @O_CHR_LIST_NO = @LIST_NO_NEW
	END TRY
	BEGIN CATCH
		SET @O_CHR_MSGTYPE = 'DE'
		SET @O_INT_MSGLEVEL = 3
		SET @O_CHR_MESSAGE = N'預存程序 [USP_OBZ020_I00] 執行失敗，無法新增名單'
		RETURN
	END CATCH

END

