USE [OB]
GO

/****** Object:  Table [dbo].[HOTAI_CO_NOMKT]    Script Date: 2026/4/20 ¤U¤È 02:37:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HOTAI_CO_NOMKT](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[CUSTO_NO] [varchar](12) NOT NULL,
	[CUST_NM] [nvarchar](10) NULL,
	[COMP_NM] [nvarchar](30) NULL,
	[COMP_ROLE] [nvarchar](20) NULL,
	[INSERT_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_HOTAI_CO_NOMKT] PRIMARY KEY CLUSTERED 
(
	[CUSTO_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO


