USE [LL]
GO

/****** Object:  Table [dbo].[LLCUSTATTRIBMF]    Script Date: 2026/4/20 ¤U¤È 02:18:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LLCUSTATTRIBMF](
	[A_PRGID] [varchar](10) NOT NULL,
	[A_USERID] [varchar](10) NOT NULL,
	[A_SYSDT] [datetime] NOT NULL,
	[U_PRGID] [varchar](10) NOT NULL,
	[U_USERID] [varchar](10) NOT NULL,
	[U_SYSDT] [datetime] NOT NULL,
	[SEQNO] [int] IDENTITY(1,1) NOT NULL,
	[CUSTID] [varchar](10) NOT NULL,
	[CNTRNO] [varchar](12) NOT NULL,
	[ATTRIBCD] [varchar](2) NOT NULL,
	[TYPE] [varchar](2) NOT NULL,
	[TYPEMEMO] [varchar](125) NOT NULL,
	[CONTENT] [varchar](125) NOT NULL,
	[BIZTYPE] [varchar](2) NOT NULL,
	[OBOUT] [varchar](1) NOT NULL,
	[STADT] [varchar](8) NOT NULL,
	[ENDDT] [varchar](8) NOT NULL,
 CONSTRAINT [PK_LLCUSTATTRIBMF] PRIMARY KEY CLUSTERED 
(
	[SEQNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_A_PRGID]  DEFAULT ('') FOR [A_PRGID]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_A_USERID]  DEFAULT ('') FOR [A_USERID]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_A_SYSDT]  DEFAULT (getdate()) FOR [A_SYSDT]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_U_PRGID]  DEFAULT ('') FOR [U_PRGID]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_U_USERID]  DEFAULT ('') FOR [U_USERID]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_U_SYSDT]  DEFAULT (getdate()) FOR [U_SYSDT]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_CUSTID]  DEFAULT ('') FOR [CUSTID]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_CNTRNO]  DEFAULT ('') FOR [CNTRNO]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_ATTRIBCD]  DEFAULT ('') FOR [ATTRIBCD]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_TYPE]  DEFAULT ('') FOR [TYPE]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_TYPEMEMO]  DEFAULT ('') FOR [TYPEMEMO]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_CONTENT]  DEFAULT ('') FOR [CONTENT]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_BIZTYPE]  DEFAULT ('01') FOR [BIZTYPE]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_OBOUT]  DEFAULT ('N') FOR [OBOUT]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_STADT]  DEFAULT ('20110125') FOR [STADT]
GO

ALTER TABLE [dbo].[LLCUSTATTRIBMF] ADD  CONSTRAINT [DF_LLCUSTATTRIBMF_ENDDT]  DEFAULT ('20991231') FOR [ENDDT]
GO


