export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  ACCOUNT_EMAIL_EXISTS: 'ACCOUNT_EMAIL_EXISTS',
  RATE_LIMITED: 'RATE_LIMITED',
  TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  ACCOUNT_EMAIL_IN_USE: 'ACCOUNT_EMAIL_IN_USE',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_SELF_DISABLE: 'ACCOUNT_SELF_DISABLE',
  ACCOUNT_LAST_ADMIN: 'ACCOUNT_LAST_ADMIN',
  VALIDATION_INVALID_ROLE: 'VALIDATION_INVALID_ROLE',
  RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  RESET_TOKEN_USED: 'AUTH_RESET_TOKEN_USED',
  RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  VALIDATION_PASSWORD_LENGTH: 'VALIDATION_PASSWORD_LENGTH',
  EMAIL_SEND_FAILED: 'SYSTEM_EMAIL_SEND_FAILED',
  ACCOUNT_SELF_RESET: 'ACCOUNT_SELF_RESET',
  // F045: Roles
  ROLE_MODIFICATION_FORBIDDEN: 'ROLE_MODIFICATION_FORBIDDEN',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  // F011: Datasource
  DS_NAME_EXISTS: 'DS_NAME_EXISTS',
  DS_NOT_FOUND: 'DS_NOT_FOUND',
  VALIDATION_INVALID_TYPE: 'VALIDATION_INVALID_TYPE',
  VALIDATION_PORT_RANGE: 'VALIDATION_PORT_RANGE',
  // F015: Test Connection
  DS_CONNECTION_FAILED: 'DS_CONNECTION_FAILED',
  DS_CONNECTION_TIMEOUT: 'DS_CONNECTION_TIMEOUT',
  DS_AUTH_FAILED: 'DS_AUTH_FAILED',
  DS_HOST_UNREACHABLE: 'DS_HOST_UNREACHABLE',
  DS_DATABASE_NOT_FOUND: 'DS_DATABASE_NOT_FOUND',
  // F017: Extraction Task
  EXTRACTION_NAME_EXISTS: 'EXTRACTION_NAME_EXISTS',
  EXTRACTION_DATASOURCE_NOT_FOUND: 'EXTRACTION_DATASOURCE_NOT_FOUND',
  EXTRACTION_INVALID_CRON: 'EXTRACTION_INVALID_CRON',
  EXTRACTION_INCREMENTAL_COLUMN_REQUIRED: 'EXTRACTION_INCREMENTAL_COLUMN_REQUIRED',
  // F019: Edit Extraction Task
  EXTRACTION_NOT_FOUND: 'EXTRACTION_NOT_FOUND',
  EXTRACTION_RUNNING: 'EXTRACTION_RUNNING',
  // F021: Raw Data
  EXTRACTION_TABLE_CREATE_FAILED: 'EXTRACTION_TABLE_CREATE_FAILED',
  EXTRACTION_SOURCE_TABLE_NOT_FOUND: 'EXTRACTION_SOURCE_TABLE_NOT_FOUND',
  // F026: Preview Raw Data
  EXTRACTION_RAW_TABLE_NOT_FOUND: 'EXTRACTION_RAW_TABLE_NOT_FOUND',
  // Datasource schema/table loading
  DATASOURCE_SCHEMA_LOAD_FAILED: 'DATASOURCE_SCHEMA_LOAD_FAILED',
  DATASOURCE_TABLE_LOAD_FAILED: 'DATASOURCE_TABLE_LOAD_FAILED',
  // F027: ETL Pipeline
  PIPELINE_NOT_FOUND: 'PIPELINE_NOT_FOUND',
  PIPELINE_NAME_EXISTS: 'PIPELINE_NAME_EXISTS',
  PIPELINE_INVALID_CONNECTION: 'PIPELINE_INVALID_CONNECTION',
  VALIDATION_INVALID_CRON: 'VALIDATION_INVALID_CRON',
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
  // F030: Execute Pipeline
  PIPELINE_RUNNING: 'PIPELINE_RUNNING',
  PIPELINE_NO_DEFINITION: 'PIPELINE_NO_DEFINITION',
  // F031: Toggle Pipeline
  PIPELINE_DRAFT_CANNOT_ENABLE: 'PIPELINE_DRAFT_CANNOT_ENABLE',
  // F037: Publish Pipeline Version
  PIPELINE_PUBLISH_REQUIRES_TEST: 'PIPELINE_PUBLISH_REQUIRES_TEST',
  PIPELINE_VERSION_ALREADY_PUBLISHED: 'PIPELINE_VERSION_ALREADY_PUBLISHED',
  PIPELINE_VERSION_NOT_FOUND: 'PIPELINE_VERSION_NOT_FOUND',
  // F032: Pipeline Logs
  PIPELINE_LOG_NOT_FOUND: 'PIPELINE_LOG_NOT_FOUND',
  // F036: Target Tables
  PIPELINE_TARGET_TABLE_NOT_FOUND: 'PIPELINE_TARGET_TABLE_NOT_FOUND',
  // F046/F047: Customer 360
  C360_CUSTOMER_NOT_FOUND: 'C360_CUSTOMER_NOT_FOUND',
  C360_SEARCH_MIN_LENGTH: 'C360_SEARCH_MIN_LENGTH',
} as const;

export const ERROR_MESSAGES = {
  INVALID_CREDENTIALS: 'Email 或密碼錯誤',
  ACCOUNT_DISABLED: '您的帳號已被停用，請聯絡管理員。',
  FORBIDDEN: '您沒有權限執行此操作。',
  RATE_LIMITED: '登入嘗試過於頻繁，請稍後再試。',
  ACCOUNT_EMAIL_EXISTS: '此 Email 已有帳號存在',
  INVALID_EMAIL: '請輸入有效的 Email 地址',
  PASSWORD_REQUIRED: '請輸入密碼',
  VALIDATION_ERROR: '請提供有效的 Email 與密碼',
  TOKEN_REVOKED: 'Session 已失效，請重新登入。',
  TOKEN_EXPIRED: 'Session 已過期，請重新登入。',
  TOKEN_MISSING: '請先登入。',
  ACCOUNT_EMAIL_IN_USE: '此 Email 已被使用',
  ACCOUNT_NOT_FOUND: '找不到指定的帳號',
  ACCOUNT_SELF_DISABLE: '您無法停用自己的帳號',
  ACCOUNT_LAST_ADMIN: '無法移除最後一位 Admin，系統必須至少保留一個 Admin 帳號。',
  VALIDATION_INVALID_ROLE: '角色值無效，必須為系統定義的 8 種角色之一',
  RESET_TOKEN_EXPIRED: '此連結已過期，請重新申請密碼重設',
  RESET_TOKEN_USED: '此連結已失效',
  RESET_TOKEN_INVALID: '重設連結無效',
  VALIDATION_PASSWORD_LENGTH: '密碼長度不得少於 8 個字元',
  EMAIL_SEND_FAILED: '郵件發送失敗，請稍後再試',
  ACCOUNT_SELF_RESET: '請透過個人設定變更您自己的密碼',
  // F045: Roles
  ROLE_MODIFICATION_FORBIDDEN: '角色為系統預設，不支援自訂新增或刪除',
  ROLE_NOT_FOUND: '找不到指定的角色',
  // F011: Datasource
  DS_NAME_EXISTS: '相同資料庫下已存在此名稱的資料來源',
  DS_NOT_FOUND: '找不到指定的資料來源',
  VALIDATION_INVALID_TYPE: '資料來源類型必須為 mysql、postgresql 或 sqlserver',
  VALIDATION_PORT_RANGE: '連接埠必須介於 1 到 65535 之間',
  // F015: Test Connection
  DS_CONNECTION_FAILED: '連線測試失敗',
  DS_CONNECTION_TIMEOUT: '連線逾時',
  DS_AUTH_FAILED: '帳號或密碼錯誤',
  DS_HOST_UNREACHABLE: '無法連線至主機',
  DS_DATABASE_NOT_FOUND: '找不到指定的資料庫',
  // F017: Extraction Task
  EXTRACTION_NAME_EXISTS: '此名稱的擷取任務已存在',
  EXTRACTION_DATASOURCE_NOT_FOUND: '指定的資料來源不存在或已被刪除',
  EXTRACTION_INVALID_CRON: '排程格式不正確，請輸入合法的 cron 表達式',
  EXTRACTION_INCREMENTAL_COLUMN_REQUIRED: '增量模式必須指定增量欄位',
  // F019: Edit Extraction Task
  EXTRACTION_NOT_FOUND: '找不到指定的擷取任務',
  EXTRACTION_RUNNING: '任務執行中，無法編輯',
  // F021: Raw Data
  EXTRACTION_TABLE_CREATE_FAILED: 'Raw Data 表建立失敗',
  EXTRACTION_SOURCE_TABLE_NOT_FOUND: '找不到來源表',
  // F026: Preview Raw Data
  EXTRACTION_RAW_TABLE_NOT_FOUND: 'Raw Data 表不存在，請先執行擷取任務',
  // Datasource schema/table loading
  DATASOURCE_SCHEMA_LOAD_FAILED: '無法載入資料來源的 Schema 列表',
  DATASOURCE_TABLE_LOAD_FAILED: '無法載入資料來源的資料表列表',
  // F027: ETL Pipeline
  PIPELINE_NOT_FOUND: '找不到指定的 Pipeline',
  PIPELINE_NAME_EXISTS: '此名稱的 Pipeline 已存在',
  PIPELINE_INVALID_CONNECTION: '連線規則違反',
  VALIDATION_INVALID_CRON: '排程格式不正確，請輸入合法的 cron 表達式',
  SYSTEM_INTERNAL_ERROR: '系統發生非預期錯誤，請稍後再試',
  // F030: Execute Pipeline
  PIPELINE_RUNNING: 'Pipeline 正在執行中',
  PIPELINE_NO_DEFINITION: 'Pipeline 尚未定義節點，無法執行',
  // F031: Toggle Pipeline
  PIPELINE_DRAFT_CANNOT_ENABLE: '需先發布 Pipeline 才能啟用',
  // F037: Publish Pipeline Version
  PIPELINE_PUBLISH_REQUIRES_TEST: '請先完成測試執行才能發布此版本',
  PIPELINE_VERSION_ALREADY_PUBLISHED: '此版本已發布',
  PIPELINE_VERSION_NOT_FOUND: '找不到指定的版本',
  // F032: Pipeline Logs
  PIPELINE_LOG_NOT_FOUND: '找不到指定的執行日誌',
  // F036: Target Tables
  PIPELINE_TARGET_TABLE_NOT_FOUND: '找不到指定的目標表',
  // F046/F047: Customer 360
  C360_CUSTOMER_NOT_FOUND: '找不到此客戶資料',
  C360_SEARCH_MIN_LENGTH: '搜尋關鍵字至少需要 2 個字元',
} as const;
