USE [CRM]
GO

/****** Object:  Table [dbo].[CRMSRVREC]    Script Date: 2026/4/20 下午 02:36:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CRMSRVREC](
	[A_PRGID] [varchar](10) NOT NULL,
	[A_USERID] [varchar](10) NOT NULL,
	[A_SYSDT] [datetime] NOT NULL,
	[U_PRGID] [varchar](10) NOT NULL,
	[U_USERID] [varchar](10) NOT NULL,
	[U_SYSDT] [datetime] NOT NULL,
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[CNTRNO] [varchar](20) NOT NULL,
	[CNTTYPE] [varchar](2) NOT NULL,
	[CNTPS] [varchar](2) NOT NULL,
	[CNTPMEMO] [varchar](100) NOT NULL,
	[CNTTEL] [varchar](2) NOT NULL,
	[CNTTMEMO] [varchar](100) NOT NULL,
	[CNTDEPT] [varchar](2) NOT NULL,
	[CNTDMEMO] [varchar](100) NOT NULL,
	[SRVTYPE] [varchar](2) NOT NULL,
	[SRVTMEMO] [varchar](100) NOT NULL,
	[CNTCONTENT] [varchar](500) NOT NULL,
	[DATEDT] [varchar](8) NOT NULL,
	[DATETIME] [varchar](4) NOT NULL,
	[R_EMAIL] [varchar](50) NOT NULL,
	[BIZTYPE] [varchar](2) NOT NULL,
	[CARNO] [varchar](10) NOT NULL,
	[UNCHECK] [varchar](2) NOT NULL,
	[RECTYPE] [varchar](2) NOT NULL,
	[RECKEY] [varchar](max) NOT NULL,
	[FAXKEY] [varchar](20) NOT NULL,
	[CUSTID] [varchar](11) NOT NULL,
	[BKWTYPE] [char](2) NOT NULL,
	[CLEARFLG] [char](2) NOT NULL,
	[CLEARDT] [char](8) NOT NULL,
	[CLEARMEMO] [varchar](500) NOT NULL,
	[CLEARUSER] [varchar](10) NOT NULL,
	[RECRESULT] [int] NOT NULL,
	[CTYPE] [varchar](2) NOT NULL,
	[SDTIME] [datetime] NULL,
	[EDTIME] [datetime] NULL,
	[LAREA] [varchar](10) NULL,
	[CALLIN] [varchar](50) NULL,
	[LAREA1] [varchar](5) NOT NULL,
	[LINETYPE] [varchar](2) NULL,
	[QTYPE] [varchar](2) NULL,
	[UCID] [varchar](20) NULL,
	[WORKITEMID] [varchar](32) NULL,
	[CONF_DT] [datetime] NULL,
	[DELAYAMT] [int] NULL,
 CONSTRAINT [PK_CRMSRVREC_TEMP] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_A_PRGID]  DEFAULT ('') FOR [A_PRGID]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_A_USERID]  DEFAULT ('') FOR [A_USERID]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_A_SYSDT]  DEFAULT (getdate()) FOR [A_SYSDT]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_U_PRGID]  DEFAULT ('') FOR [U_PRGID]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_U_USERID]  DEFAULT ('') FOR [U_USERID]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_U_SYSDT]  DEFAULT (getdate()) FOR [U_SYSDT]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTRNO]  DEFAULT ('') FOR [CNTRNO]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTTYPE]  DEFAULT ('') FOR [CNTTYPE]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTPS]  DEFAULT ('') FOR [CNTPS]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTPMEMO]  DEFAULT ('') FOR [CNTPMEMO]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTTEL]  DEFAULT ('') FOR [CNTTEL]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTTMEMO]  DEFAULT ('') FOR [CNTTMEMO]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTDEPT]  DEFAULT ('') FOR [CNTDEPT]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTDMEMO]  DEFAULT ('') FOR [CNTDMEMO]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_SRVTYPE]  DEFAULT ('') FOR [SRVTYPE]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_SRVTMEMO]  DEFAULT ('') FOR [SRVTMEMO]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CNTCONTENT]  DEFAULT ('') FOR [CNTCONTENT]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_DATEDT]  DEFAULT ('') FOR [DATEDT]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_DATETIME]  DEFAULT ('') FOR [DATETIME]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_R_EMAIL]  DEFAULT ('') FOR [R_EMAIL]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_BIZTYPE]  DEFAULT ('') FOR [BIZTYPE]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CARNO]  DEFAULT ('') FOR [CARNO]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_UNCHECK]  DEFAULT ('N') FOR [UNCHECK]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_RECTYPE]  DEFAULT ('') FOR [RECTYPE]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_RECKEY]  DEFAULT ('') FOR [RECKEY]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_FAXKEY]  DEFAULT ('') FOR [FAXKEY]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CUSTID]  DEFAULT ('') FOR [CUSTID]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_BKWTYPE]  DEFAULT ('') FOR [BKWTYPE]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CLEARFLG]  DEFAULT ('N') FOR [CLEARFLG]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CLEARDT]  DEFAULT ('') FOR [CLEARDT]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CLEARMEMO]  DEFAULT ('') FOR [CLEARMEMO]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CLEARUSER]  DEFAULT ('') FOR [CLEARUSER]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_RECRESULT]  DEFAULT ((0)) FOR [RECRESULT]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  CONSTRAINT [DF_CRMSRVREC_TEMP_CTYPE]  DEFAULT ('') FOR [CTYPE]
GO

ALTER TABLE [dbo].[CRMSRVREC] ADD  DEFAULT ('') FOR [LAREA1]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'BKWTYPE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'BKWTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'結案區分' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'CLEARFLG'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'結案日' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'CLEARDT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'結案備註' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'CLEARMEMO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'結案窗口' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'CLEARUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'地區別' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'LAREA'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'來電顯示號碼' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'CALLIN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'客戶滿意度調查（電銷：外部名單流水號）' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CRMSRVREC', @level2type=N'COLUMN',@level2name=N'UCID'
GO


