USE [ZZIPPROD]
GO

/****** Object:  Table [dbo].[APPLNO_M_CRM]    Script Date: 2026/4/20 ¤U¤È 02:48:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APPLNO_M_CRM](
	[ORGNO] [nvarchar](2) NOT NULL,
	[APPL_NO] [nvarchar](10) NOT NULL,
	[CUSTO_NO] [nvarchar](11) NOT NULL,
	[CUST_NAME] [nvarchar](90) NULL,
	[LIC_NO] [varchar](10) NULL,
	[STA_CODE_NA] [nvarchar](40) NULL,
	[PROJECT_TP] [nvarchar](40) NULL,
	[SPEC_NO] [nvarchar](10) NULL,
	[SPEC_NAME] [nvarchar](45) NULL,
	[DEPT_NAME] [nvarchar](30) NULL,
	[PAY_RESOUC_CODE] [nvarchar](2) NULL,
	[BREAK_PCT] [numeric](5, 0) NULL,
	[EXTEND_DAY] [numeric](2, 0) NULL,
	[PAY_RESOUC] [nvarchar](40) NULL,
	[COMMUTE] [nvarchar](90) NULL,
	[CYCLE_PAY_NA] [nvarchar](40) NULL,
	[CYCLE_PAY_VAL] [nvarchar](2) NULL,
	[DEAL_NUM] [numeric](3, 0) NULL,
	[PRO_RATE] [numeric](6, 3) NULL,
	[B_CASE_IRR] [numeric](5, 2) NULL,
	[FIRST_PAY_DT] [datetime] NULL,
	[FAPCON_DT] [datetime] NULL,
	[MATURITY_DT] [datetime] NULL,
	[DEAL_MARK] [nvarchar](2) NULL,
	[PAY_WAY] [nvarchar](2) NULL,
	[LOAN_TOTAMT] [numeric](18, 0) NULL,
	[LOAN_CAPITAL] [numeric](18, 0) NULL,
	[LOAN_ODDAMT] [numeric](18, 0) NULL,
	[COMMISSION] [numeric](15, 0) NULL,
	[SETTLE_DATE] [datetime] NULL,
	[LOAN_RATE] [numeric](5, 2) NULL,
	[STA_CODE] [nvarchar](2) NOT NULL,
	[OFI_DATE] [datetime] NULL,
	[DEPT_ID] [nvarchar](6) NOT NULL,
	[PAY_WAY_NA] [nvarchar](30) NULL,
	[BRNH_NO] [nvarchar](5) NULL,
	[DLR_NO] [nvarchar](4) NULL,
	[BROKER] [nvarchar](60) NULL,
	[SALES_NO] [nvarchar](14) NULL,
	[BROKER_AGENT] [nvarchar](60) NULL,
	[HFS_SALES] [nvarchar](14) NULL,
	[SALES] [nvarchar](60) NULL,
	[AGENT_HEAD_ID] [nvarchar](11) NULL,
	[PROMOTER_DEPT] [nvarchar](60) NULL,
	[AGENT_ID] [nvarchar](11) NULL,
	[PROMOTER] [nvarchar](60) NULL,
	[BRAND_NO] [nvarchar](2) NULL,
	[BRAND_NAME] [nvarchar](40) NULL,
	[CAR_NAME] [nvarchar](30) NULL,
	[INQUIRY] [nvarchar](10) NULL,
	[APPROVAL] [nvarchar](10) NULL,
	[MANAGER_LIMIT] [nvarchar](2) NULL,
	[SPEC_MK_NA] [nvarchar](40) NULL,
	[SPEC_TYPE_NA] [nvarchar](40) NULL,
	[ATM_BUSINESS] [nvarchar](4) NULL,
	[NO_DUTY] [nvarchar](1) NULL,
	[YEAR_PRODU] [nvarchar](4) NULL,
	[DLR_NAME] [varchar](30) NULL,
	[BRNH_NAME] [varchar](30) NULL,
	[PROJECT_TP_CD] [nvarchar](2) NULL,
	[APPL_DATE] [datetime] NULL,
	[APMACC_MEMO] [nvarchar](1000) NULL,
	[SALES_STS_NA] [nvarchar](30) NULL,
	[SUB_CODE] [nvarchar](2) NULL,
	[CC_NBR] [nvarchar](5) NULL,
	[THROU_MON] [numeric](8, 0) NULL,
	[FUND_SRC] [varchar](2) NULL,
	[SECRET_FLG] [varchar](1) NULL,
	[RATE_CHOICE] [varchar](30) NULL,
	[PER_INFO] [nvarchar](30) NULL,
	[TIE_DOWN_NUM] [int] NULL,
	[REST_AMT] [numeric](8, 0) NULL,
	[OVER_TIE_NUM] [int] NULL,
	[OPEN_CODE] [varchar](1) NULL,
	[EMPLID] [varchar](10) NULL,
	[EMPLID_DEPTID] [varchar](6) NULL,
	[CASE_TYPE] [varchar](2) NULL,
	[HOTAI_AGREE] [varchar](10) NULL,
	[CALL_DEPT] [varchar](4) NULL,
	[C_CLASS] [varchar](1) NULL
) ON [PRIMARY]
GO


